name: Playwright tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  report:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: npm install

      - name: Install playwright
        run: npm install playwright

      - name: Run tests
        run: npx playwright test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Test Report
          path: playwright-report
          retention-days: 30
